[project]
site_name = "PARE - Planificación y Administración de Redes y Equipos"
site_url = "https://raul-profesor.github.io/PARE"
dev_addr = "localhost:9090"
extra_css = ["stylesheets/extra.css"]
# Tema Material
nav = [
    {Home = "index.md"},
    {Switch = [
        "SecSwitches.md",
        "dtp.md",
        "cheatsheet_routers.md"
    ]},
    {Enrutamiento = [
        "routers_y_rutas_estaticas.md",
        "rutas_dinamicas.md",
        "RIP_RIPv2.md",
        "ospf.md"
    ]}
]

[project.theme]
name = "material"
language = "es"
font.text = "Inter"

features = [
    "navigation.instant",
    "navigation.instant",
    "navigation.instant.progress",
    "navigation.tabs",
    "navigation.expand",
    "navigation.path",
    "toc.follow",
    "navigation.top",
    "content.footnote.tooltips"
]
# Configuración de paletas de colores
[[project.theme.palette]]
media = "(prefers-color-scheme: light)"
scheme = "default"
primary = "indigo"
accent = "blue"
toggle.icon = "lucide/sun"
toggle.name = "Cambiar a modo oscuro"

[[project.theme.palette]]
media = "(prefers-color-scheme: dark)"
scheme = "slate"
primary = "black"
accent = "deep orange"
toggle.icon = "lucide/moon"
toggle.name = "Cambiar a modo claro"


[project.markdown_extensions.md_in_html]
[project.markdown_extensions.pymdownx.blocks.caption] 
types = [
    "caption",
    "table",
    "figure",
    { name = "figura", prefix = "Figura {}. " }
]
auto=true
[project.markdown_extensions.pymdownx.highlight]
anchor_linenums = true
line_spans = "__span"
pygments_lang_class = true
[project.markdown_extensions.pymdownx.inlinehilite]
[project.markdown_extensions.pymdownx.snippets]
[project.markdown_extensions.pymdownx.superfences]
[project.markdown_extensions.footnotes]
[project.markdown_extensions.pymdownx.caret]
[project.markdown_extensions.pymdownx.keys]
[project.markdown_extensions.pymdownx.mark]
[project.markdown_extensions.pymdownx.tilde]
[project.markdown_extensions.attr_list]
[project.markdown_extensions.admonition]
[project.markdown_extensions.pymdownx.details]

# Características del tema
#